# Generated by Django 4.0.4 on 2022-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuarios_contato_fk_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='token',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
