# Generated by Django 4.0.4 on 2022-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_usuarios_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
